# encoding: utf-8
# module pandas._libs.tslibs.np_datetime
# from /var/www/newsbytes/CPP/venv/lib/python3.6/site-packages/pandas/_libs/tslibs/np_datetime.cpython-36m-x86_64-linux-gnu.so
# by generator 1.147
# no doc

# imports
import builtins as __builtins__ # <module 'builtins' (built-in)>

# no functions
# classes

class OutOfBoundsDatetime(ValueError):
    # no doc
    def __init__(self, *args, **kwargs): # real signature unknown
        pass

    __weakref__ = property(lambda self: object(), lambda self, v: None, lambda self: None)  # default
    """list of weak references to the object (if defined)"""



# variables with complex values

__loader__ = None # (!) real value is '<_frozen_importlib_external.ExtensionFileLoader object at 0x7fe7fbd3ae10>'

__pyx_capi__ = {
    '_string_to_dts': None, # (!) real value is '<capsule object "int (PyObject *, npy_datetimestruct *, int *, int *)" at 0x7fe7fbd511b0>'
    'check_dts_bounds': None, # (!) real value is '<capsule object "PyObject *(npy_datetimestruct *)" at 0x7fe7fbd8af90>'
    'cmp_scalar': None, # (!) real value is '<capsule object "int (__pyx_t_5numpy_int64_t, __pyx_t_5numpy_int64_t, int)" at 0x7fe7fbc99d80>'
    'dt64_to_dtstruct': None, # (!) real value is '<capsule object "void (__pyx_t_5numpy_int64_t, npy_datetimestruct *)" at 0x7fe7fbd51060>'
    'dtstruct_to_dt64': None, # (!) real value is '<capsule object "__pyx_t_5numpy_int64_t (npy_datetimestruct *)" at 0x7fe7fbd51030>'
    'get_datetime64_unit': None, # (!) real value is '<capsule object "NPY_DATETIMEUNIT (PyObject *)" at 0x7fe7fbd51180>'
    'get_datetime64_value': None, # (!) real value is '<capsule object "npy_datetime (PyObject *)" at 0x7fe7fbd51120>'
    'get_timedelta64_value': None, # (!) real value is '<capsule object "npy_timedelta (PyObject *)" at 0x7fe7fbd51150>'
    'pydate_to_dt64': None, # (!) real value is '<capsule object "__pyx_t_5numpy_int64_t (PyDateTime_Date *, npy_datetimestruct *)" at 0x7fe7fbd510f0>'
    'pydatetime_to_dt64': None, # (!) real value is '<capsule object "__pyx_t_5numpy_int64_t (PyDateTime_DateTime *, npy_datetimestruct *)" at 0x7fe7fbd510c0>'
    'reverse_ops': None, # (!) real value is '<capsule object "int [6]" at 0x7fe7fbc99d20>'
    'td64_to_tdstruct': None, # (!) real value is '<capsule object "void (__pyx_t_5numpy_int64_t, pandas_timedeltastruct *)" at 0x7fe7fbd51090>'
}

__spec__ = None # (!) real value is "ModuleSpec(name='pandas._libs.tslibs.np_datetime', loader=<_frozen_importlib_external.ExtensionFileLoader object at 0x7fe7fbd3ae10>, origin='/var/www/newsbytes/CPP/venv/lib/python3.6/site-packages/pandas/_libs/tslibs/np_datetime.cpython-36m-x86_64-linux-gnu.so')"

__test__ = {}

